# https://github.com/AlexxIT/builder/blob/master/builder.sh
name: eufyp2pstream
description: Eufy P2P camera streaming application
url: http://homeassistant:8123/local_eufyp2pstream
arch: [amd64, aarch64, i386, armv7]

# https://developers.home-assistant.io/docs/add-ons/configuration
version: 0.2.2-alpha
slug: eufyp2pstream
init: false
startup: application
panel_icon: mdi:camera-wireless
map: [config, media]
host_network: false
options:
  eufy_security_ws_port: 3000
  eufy_device_serial: ""
schema:
  eufy_security_ws_port: port
  eufy_device_serial: str
ports: { "63336/tcp": 63336, "63337/tcp": 63337, "63338/tcp": 63338 }
